name: fishmaster
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  geocoding: ">1.0.0 <2.3.0-beta"
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  location: ^8.0.0
  http: ^1.3.0
  intl: ^0.20.2
  get:
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.8.0
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.5.2
  flutter_compass: ^0.8.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/logos/
      - assets/images/
      - assets/response4.json
      - assets/port_icon.png
      - assets/ports.json
      - assets/gear_time.json


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
